Name:           ros-hydro-rtabmap-ros
Version:        0.8.1
Release:        0%{?dist}
Summary:        ROS rtabmap_ros package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-class-loader
Requires:       ros-hydro-cv-bridge
Requires:       ros-hydro-dynamic-reconfigure
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-image-transport
Requires:       ros-hydro-image-transport-plugins
Requires:       ros-hydro-laser-geometry
Requires:       ros-hydro-message-filters
Requires:       ros-hydro-nav-msgs
Requires:       ros-hydro-nodelet
Requires:       ros-hydro-pcl-conversions
Requires:       ros-hydro-pcl-ros
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-rospy
Requires:       ros-hydro-rtabmap
Requires:       ros-hydro-rviz
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-std-msgs
Requires:       ros-hydro-std-srvs
Requires:       ros-hydro-stereo-msgs
Requires:       ros-hydro-tf
Requires:       ros-hydro-tf-conversions
BuildRequires:  pcl-devel
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-class-loader
BuildRequires:  ros-hydro-cv-bridge
BuildRequires:  ros-hydro-dynamic-reconfigure
BuildRequires:  ros-hydro-genmsg
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-image-transport
BuildRequires:  ros-hydro-laser-geometry
BuildRequires:  ros-hydro-message-filters
BuildRequires:  ros-hydro-nav-msgs
BuildRequires:  ros-hydro-nodelet
BuildRequires:  ros-hydro-pcl-conversions
BuildRequires:  ros-hydro-pcl-ros
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-rtabmap
BuildRequires:  ros-hydro-rviz
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-std-msgs
BuildRequires:  ros-hydro-std-srvs
BuildRequires:  ros-hydro-stereo-msgs
BuildRequires:  ros-hydro-tf
BuildRequires:  ros-hydro-tf-conversions

%description
RTAB-Map's ros-pkg. RTAB-Map is an RGB-D SLAM approach with real-time
constraints.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Sun Jan 11 2015 Mathieu Labbe <matlabbe@gmail.com> - 0.8.1-0
- Autogenerated by Bloom

* Sun Dec 14 2014 Mathieu Labbe <matlabbe@gmail.com> - 0.8.0-0
- Autogenerated by Bloom

* Tue Dec 02 2014 Mathieu Labbe <matlabbe@gmail.com> - 0.7.3-0
- Autogenerated by Bloom

* Tue Dec 02 2014 Mathieu Labbe <matlabbe@gmail.com> - 0.7.3-1
- Autogenerated by Bloom

* Tue Nov 25 2014 Mathieu Labbe <matlabbe@gmail.com> - 0.7.1-0
- Autogenerated by Bloom

