name: docker

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        docker_tag: [kinetic, kinetic-latest, melodic, melodic-latest, noetic, noetic-latest]
        include:
        - docker_tag: kinetic
          docker_path: 'kinetic'
        - docker_tag: kinetic-latest
          docker_path: 'kinetic/latest'
        - docker_tag: melodic
          docker_path: 'melodic'
        - docker_tag: melodic-latest
          docker_path: 'melodic/latest'
        - docker_tag: noetic
          docker_path: 'noetic'
        - docker_tag: noetic-latest
          docker_path: 'noetic/latest'
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/${{ matrix.docker_path }}
          push: true
          build-args: |
            CACHE_DATE=${{ github.head_ref }}.${{ github.sha }}
          tags: introlab3it/rtabmap_ros:${{ matrix.docker_tag }}
          cache-from: type=registry,ref=introlab3it/rtabmap_ros:${{ matrix.docker_tag }}
          cache-to: type=inline

